version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install

  build:
    commands:
      - npm run build

  post_build:
    commands:
      - chmod +x upload-assets.sh
      - ./upload-assets.sh
      - echo "Deployed to S3"
      - >
        curl -X POST "https://api.fastly.com/service/$FASTLY_SERVICE_ID/purge_all"
        -H "Fastly-Key: $FASTLY_API_KEY"
        -H "Accept: application/json"

artifacts:
  files:
    - '**/*'
  base-directory: dist
