version: 0.2

phases:
  install:
    commands:
      - echo "No build needed. Static files already present."
  build:
    commands:
      - echo "Skipping build step."
  post_build:
    commands:
      - chmod +x upload-assets.sh
      - ./upload-assets.sh
      - echo "Files uploaded to S3"
      - >
        curl -X POST "https://api.fastly.com/service/$FASTLY_SERVICE_ID/purge_all" \
        -H "Fastly-Key: $FASTLY_API_KEY" \
        -H "Accept: application/json"

artifacts:
  files:
    - '**/*'
  base-directory: dist
